version: 2.1
jobs:
  one:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "running npm install  >>>>>"
      - run: sleep 10
      - run:
          name: installing necessary files
          command: npm install
          background: true

  two:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: node app.js
      - run: npm run test
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
 