version: 2.1
jobs:
  one:
    docker:
      - image: circle/node@1.1
    steps:
      - checkout
      - run: echo "running npm install"
      - run: sleep 10
      - run: npm install
  two:
    docker:
      - image: circleci/node@1.1
    steps:
      - checkout
      - run: node app.js
      - run: npm run test
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
 